name: Vize Kontrol Botu
on:
  schedule:
    - cron: '*/15 * * * *' # Her 15 dakikada bir çalıştır
  workflow_dispatch: # İstediğimizde elimizle çalıştırmak için

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Python Kur
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Gerekli Paketleri Yükle
        run: pip install requests
      - name: Botu Çalıştır
        run: python bot.py
- name: Sonucu Kaydet ve Yükle
        run: |
          git config --global user.name 'Vize Botu'
          git config --global user.email 'bot@vize.com'
          git add sonuc.json
          git commit -m "Güncel randevu durumu" || echo "Değişiklik yok"
          git push
