name: Vize Radar Otomatik
on:
  schedule:
    - cron: '*/5 * * * *'  # 5 dakikada bir çalışır
  workflow_dispatch:      # Manuel başlatma butonu

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write     # Dosya yüklemek için şart
    env:
      TZ: Europe/Istanbul  # Sunucu saatini Türkiye yapar
    steps:
      - uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Paketleri Yukle
        run: pip install requests

      - name: Botu Calistir
        run: python bot.py

      - name: Veriyi Depoya Yukle
        run: |
          git config --global user.name 'vize-botu'
          git config --global user.email 'bot@vize.com'
          git add sonuc.json
          git commit -m "Güncelleme: $(date +'%d/%m/%Y %H:%M')" || echo "Degisiklik yok"
          git push
